# Generated by Django 3.1.7 on 2021-02-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered')], max_length=250, null=True),
        ),
    ]
