# Generated by Django 3.1.7 on 2021-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210228_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tag_ids',
            field=models.ManyToManyField(to='accounts.Tag', verbose_name='Tag Ids'),
        ),
    ]
